//
//  CharacterDetailsInteractor.swift
//  RickAndMorty
//
//  Created by Ricardo Ruiz on 12/12/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterDetailsBusinessLogic
{
    func doSomething(request: CharacterDetails.Something.Request)
}

protocol CharacterDetailsDataStore
{
    var character : Character? { get set }
}

class CharacterDetailsInteractor: CharacterDetailsBusinessLogic, CharacterDetailsDataStore
{
    var character: Character?
    
    var presenter: CharacterDetailsPresentationLogic?
    var worker: CharacterDetailsWorker?
    
    // MARK: Do something
    
    func doSomething(request: CharacterDetails.Something.Request)
    {
        worker = CharacterDetailsWorker()
        worker?.doSomeWork()
        
        let response = CharacterDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
