//
//  CharacterListWorker.swift
//  RickAndMorty
//
//  Created by Ricardo Ruiz on 12/12/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CharacterListWorker
{
    func loadCharacterList(completionHandler: @escaping ((CharacterListResult) -> Void))
    {
        if let url = URL(string: "https://rickandmortyapi.com/api/character/") {
            URLSession.shared.dataTask(with: url) { data, response, error in
                if let data = data {
                    do {
                        let characterListResult = try JSONDecoder().decode(CharacterListResult.self, from: data)
                        DispatchQueue.main.async {
                            completionHandler(characterListResult)
                        }
                    } catch let error {
                        print(error)
                    }
                }
            }.resume()
        }
    }
}
