//
//  CharacterListPresenter.swift
//  RickAndMorty
//
//  Created by Ricardo Ruiz on 12/12/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterListPresentationLogic
{
    func presentCharacterList(response: CharacterList.LoadCharacters.Response)
}

class CharacterListPresenter: CharacterListPresentationLogic
{
    weak var viewController: CharacterListDisplayLogic?
    
    // MARK: Do something
    
    func presentCharacterList(response: CharacterList.LoadCharacters.Response)
    {
        let viewModel = CharacterList.LoadCharacters.ViewModel(characterListResult: response.characterListResult.results)
        viewController?.displayCharacterList(viewModel: viewModel)
    }
}
