//
//  CharacterListInteractor.swift
//  RickAndMorty
//
//  Created by Ricardo Ruiz on 12/12/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterListBusinessLogic
{
    func loadCharacterList(request: CharacterList.LoadCharacters.Request)    
}

protocol CharacterListDataStore
{
    var character: Character? { get set }
}

class CharacterListInteractor: CharacterListBusinessLogic, CharacterListDataStore
{
    var character: Character?
    
    var presenter: CharacterListPresentationLogic?
    var worker: CharacterListWorker? = CharacterListWorker()
    
    // MARK: Do something
    
    func loadCharacterList(request: CharacterList.LoadCharacters.Request)
    {
        worker?.loadCharacterList { characterListresult in
            let response = CharacterList.LoadCharacters.Response(characterListResult: characterListresult)
            self.presenter?.presentCharacterList(response: response)
        }
    }
}
