//
//  CharacterListWorkerTests.swift
//  RickAndMorty
//
//  Created by Ricardo Ruiz on 13/12/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import RickAndMorty
import XCTest

class CharacterListWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: CharacterListWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupCharacterListWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupCharacterListWorker()
  {
    sut = CharacterListWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testLoadCharacters()
  {
    // Given
    
    // When
    sut.loadCharacterList { (characters) in
        XCTAssert(characters.results.count == 20, "20 characters should be loaded")
    }
    
    // Then
  }
}
